server:
  port: 4000

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml

spring:
  datasource:
    url: jdbc:mysql://database-1.cdvdbxhzvgow.ap-northeast-2.rds.amazonaws.com/sns?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowMultiQueries=true
    username: ssafy
    password: ssafyssafy